### PR TITLE
Safe check that picker exists before destroy

### PR DESCRIPTION
**Pull request by offirgolan**

### CODE REVIEW

**Comment by jasonmit** [comment]
I wonder if the guard is masking another bug given that instance prop is setup in didInsertElement.  Can you add a description explaining where this was unset.

**Comment by offirgolan** [comment]
Sure.

I currently have a model with a hasMany relationship (lets call the hasMany relationship `friends`). For each friend I render a template with a date picker. When you click a `cancel` button, I do a `model.rollbackAttributes()` which removes all friends from the original model. Thats when I ran into this issue.

**Comment by jasonmit** [comment]
What version of Ember?  Sounds more like an ember bug.  I would expect there always be an insert for every destroy element.

**Comment by jasonmit** [comment]
I'm fine with merging this, just want to uncover what is causing it to be needed.

**Comment by offirgolan** [comment]
```
Ember: 2.4.4
Ember Data: 2.4.3
```

Keep this open for now. Maybe I can find a way around this.

**Comment by offirgolan** [comment]
Im gonna go ahead and close this for now. I was able to take a different approach which did not expose this issue.

**Pull request closed without merging**
