### PR TITLE
use latest ember-cli-moment-shim

### PR DESCRIPTION
**Pull request by jasonmit**

### CODE REVIEW

**Comment by koryteg** [comment]
you should merge this in dude. I got errors installing. without it.

**Comment by claudiocro** [comment]
Thank you!

@jasonmit would you like to have commit rights for this project?

**Comment by jasonmit** [comment]
@claudiocro sounds good, willing to help out

**Comment by claudiocro** [comment]
@jasonmit the invitation is on the way.

I just introduced https://github.com/semantic-release/semantic-release to this project, so every push to `master` branch will trigger a version (create changelog, create a github tag, publish to npm).

I would like to use feature branches to push changes to `master` so we can review each other. Is this ok for you? If needed we also can open a `development` branch where we work on and whenever we want a version to be release we just merge the `development` branch to `master`.

**Comment by koryteg** [comment]
you guys rock.

**Comment by jasonmit** [comment]
@claudiocro Sounds good to me, I usually subscribe to feature branches unless it's a quick no-CI (doc change).

**Pull request merged**
