### PR TITLE
update eonasdan-bootstrap-datetimepicker

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by elanclarkson** [comment]
+1 took me way too long to figure out I need this PR.

**Comment by TopsyCM** [comment]
Does the eonasdan-bootstrap-datetimepicker version need to be bumped in the package.json, too?

**Comment by kellyselden** [comment]
@TopsyCM Nope. That is either not used, or only used for testing.

**Comment by franzliedke** [comment]
@jasonmit Can we get a new release with these?

**Comment by jasonmit** [comment]
@franzliedke released as 1.1.0

**Comment by franzliedke** [comment]
Thanks a lot!

**Pull request merged**
